apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "common.labels" . | indent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.identifier }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        env:
        - name: UTTU_API_URL
          valueFrom:
            configMapKeyRef:
              key: UTTU_API_URL
              name: {{ .Values.configMapMount.name }}
        - name: ORGANISATIONS_API_URL
          valueFrom:
            configMapKeyRef:
              key: ORGANISATIONS_API_URL
              name: {{ .Values.configMapMount.name }}
        - name: LOG_FORWARD_PATHS
          valueFrom:
            configMapKeyRef:
              key: LOG_FORWARD_PATHS
              name: {{ .Values.configMapMount.name }}
        - name: PUBLIC_URL
          valueFrom:
            configMapKeyRef:
              key: PUBLIC_URL
              name: {{ .Values.configMapMount.name }}
        - name: AUTH0_DOMAIN
          valueFrom:
            configMapKeyRef:
              key: AUTH0_DOMAIN
              name: {{ .Values.configMapMount.name }}
        - name: AUTH0_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: AUTH0_CLIENT_ID
              name: {{ .Values.configMapMount.name }}
        - name: AUTH0_AUDIENCE
          valueFrom:
            configMapKeyRef:
              key: AUTH0_AUDIENCE
              name: {{ .Values.configMapMount.name }}
        - name: AUTH0_CLAIMS_NAMESPACE
          valueFrom:
            configMapKeyRef:
              key: AUTH0_CLAIMS_NAMESPACE
              name: {{ .Values.configMapMount.name }}
        - name: ENABLE_LEGACY_ORGANISATIONS_FILTER
          valueFrom:
            configMapKeyRef:
              key: ENABLE_LEGACY_ORGANISATIONS_FILTER
              name: {{ .Values.configMapMount.name }}
        - name: TZ
          value: Europe/Oslo
        - name: ENVIRONMENT
          value: {{ .Values.env }}
        resources:
          limits:
            cpu: {{ .Values.resources.cpuLimit }}
            memory: {{ .Values.resources.memLimit }}
          requests:
            cpu: {{ .Values.resources.cpuRequest }}
            memory: {{ .Values.resources.memRequest }}
        ports:
          - containerPort: {{ .Values.service.http.internalPort }}
            protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: {{ .Values.service.http.internalPort }}
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 31
