env: staging

configMap:
  authServerUrl: https://kc-stage.devstage.entur.io/auth
  logForwardPaths: "true"
  organisationsApiUrl: https://api.staging.entur.io/organisations/v1/register
  publicUrl: /
  uttuApiUrl: https://api.staging.entur.io/timetable-admin/v1/flexible-lines

ingress:
    enabled: true
    stagingIp: 35.233.47.68
